
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

#nullable disable

namespace SqlOperationsEntityFrameworkCore.Models
{

    /// <summary>
    /// Class which represents products in NorthWind database.
    /// </summary>
    /// <remarks>
    /// Code was generated by EF Power Tools, Karen added INotifyPropertyChanged
    /// </remarks>
    public partial class Products
    {
        public int ProductId { get; set; }
        [RegularExpression("^.{3,}$", ErrorMessage = "{0} Minimum 3 characters required")]
        [Required(ErrorMessage = "{0} Required")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Invalid {0}")]
        public string ProductName { get; set; }

        public int? SupplierId { get; set; }
        public int? CategoryId { get; set; }

        public string QuantityPerUnit { get; set; }

        public decimal? UnitPrice { get; set; }

        public short? UnitsInStock { get; set; }

        public short? UnitsOnOrder { get; set; }

        public short? ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
        public DateTime? DiscontinuedDate { get; set; }

        public virtual Categories Category { get; set; }
        public virtual Suppliers Supplier { get; set; }
       

    }
}